const USER_ROLES = {
  ADMIN: 'admin',
  BUYER: 'buyer',
  SELLER: 'seller'
};

const PRODUCT_STATUSES = {
  ACTIVE: 'active',
  INACTIVE: 'inactive'
};

const SELLER_DOCUMENT_TYPES = {
  CAC: 'cac',
  PROOF_OF_ADDRESS: 'proof_of_address'
};

const SELLER_VERIFICATION_STATUSES = {
  PENDING: 'pending',
  VERIFIED: 'verified',
  REJECTED: 'rejected'
};

const ORDER_STATUSES = {
  CANCELLED: 'cancelled',
  CONFIRMED: 'confirmed',
  DELIVERED: 'delivered',
  DISPUTED: 'disputed',
  IN_TRANSIT: 'in_transit',
  PENDING_PAYMENT: 'pending_payment',
  PICKED_UP: 'picked_up'
};

const ORDER_ITEM_STATUSES = {
  CANCELLED: 'cancelled',
  DELIVERED: 'delivered',
  PENDING: 'pending',
  PICKED_UP: 'picked_up',
  READY_FOR_PICKUP: 'ready_for_pickup'
};

const PAYMENT_METHODS = {
  BANK_TRANSFER: 'bank_transfer',
  PAYSTACK: 'paystack',
  USSD: 'ussd'
};

const PAYMENT_STATUSES = {
  CANCELLED: 'cancelled',
  FAILED: 'failed',
  PAID: 'paid',
  PENDING: 'pending'
};

const PAYOUT_STATUSES = {
  APPROVED: 'approved',
  PAID: 'paid',
  REQUESTED: 'requested',
  REJECTED: 'rejected'
};

const ERROR_CODES = {
  AUTH_REQUIRED: 'AUTH_REQUIRED',
  CART_EMPTY: 'CART_EMPTY',
  CONFLICT: 'CONFLICT',
  FORBIDDEN: 'FORBIDDEN',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_RESET_TOKEN: 'INVALID_RESET_TOKEN',
  NOT_FOUND: 'NOT_FOUND',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  PAYMENT_CONFIGURATION_ERROR: 'PAYMENT_CONFIGURATION_ERROR',
  PAYMENT_INITIALIZATION_FAILED: 'PAYMENT_INITIALIZATION_FAILED',
  PAYMENT_VERIFICATION_FAILED: 'PAYMENT_VERIFICATION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  VALIDATION_ERROR: 'VALIDATION_ERROR'
};

module.exports = {
  ORDER_ITEM_STATUSES,
  ORDER_STATUSES,
  PAYMENT_METHODS,
  PAYMENT_STATUSES,
  PAYOUT_STATUSES,
  PRODUCT_STATUSES,
  SELLER_DOCUMENT_TYPES,
  SELLER_VERIFICATION_STATUSES,
  USER_ROLES,
  ERROR_CODES
};
