INSERT INTO products (
  id,
  seller_id,
  title,
  description,
  category_id,
  part_number,
  `condition`,
  price_kobo,
  stock_qty,
  location,
  seller_business_name,
  seller_rating,
  status
)
VALUES
  (
    4001,
    9001,
    'Front Brake Pad Set for Toyota Camry',
    'Durable ceramic front brake pad set designed for reliable everyday stopping power on Toyota Camry sedans.',
    1002,
    'FBP-CAM-07011',
    'new',
    1850000,
    18,
    'Lagos',
    'Prime Auto Hub',
    4.6,
    'active'
  ),
  (
    4002,
    9002,
    'Rear Shock Absorber Pair for Honda Accord',
    'Gas-filled rear shock absorber pair built to restore ride comfort and handling for late-model Honda Accord vehicles.',
    1003,
    'RSA-ACC-0812',
    'new',
    4200000,
    9,
    'Abuja',
    'Savannah Parts Depot',
    4.2,
    'active'
  ),
  (
    4003,
    9003,
    'Air Filter for Toyota Corolla 2014-2019',
    'OEM-style engine air filter that improves airflow and keeps dust out of the intake system.',
    1005,
    'AF-COR-1419',
    'new',
    650000,
    32,
    'Port Harcourt',
    'Naija OEM Spares',
    4.8,
    'active'
  ),
  (
    4004,
    9004,
    'Starter Motor for Lexus RX 330',
    'Refurbished starter motor tested for dependable ignition performance on compatible Lexus and Toyota SUVs.',
    1004,
    'SM-RX330-0406',
    'refurbished',
    3800000,
    4,
    'Lagos',
    'Elite Mobility Parts',
    4.9,
    'active'
  ),
  (
    4005,
    9005,
    'Fuel Pump Assembly for Toyota Hilux',
    'Clean used fuel pump assembly sourced for Toyota Hilux pickups and inspected before listing.',
    1001,
    'FPA-HIL-1215',
    'used',
    2750000,
    6,
    'Kano',
    'Northern Truck Parts',
    4.1,
    'active'
  )
ON DUPLICATE KEY UPDATE
  seller_id = VALUES(seller_id),
  title = VALUES(title),
  description = VALUES(description),
  category_id = VALUES(category_id),
  part_number = VALUES(part_number),
  `condition` = VALUES(`condition`),
  price_kobo = VALUES(price_kobo),
  stock_qty = VALUES(stock_qty),
  location = VALUES(location),
  seller_business_name = VALUES(seller_business_name),
  seller_rating = VALUES(seller_rating),
  status = VALUES(status),
  updated_at = CURRENT_TIMESTAMP;
