INSERT INTO blog_posts (
  id,
  category_id,
  title,
  slug,
  excerpt,
  body,
  featured_image_url,
  featured_image_alt,
  author_display_name,
  author_avatar_url,
  read_time_minutes,
  status,
  published_at,
  view_count,
  created_at,
  updated_at
)
VALUES
  (
    8301,
    8101,
    'How to Know When Brake Pads Need Immediate Replacement',
    'how-to-know-when-brake-pads-need-immediate-replacement',
    'A quick workshop checklist for spotting worn brake pads before noise, vibration, and unsafe stopping distance become expensive problems.',
    '<p>Brake pads usually warn drivers long before complete failure, but many owners miss the early signs during busy work weeks.</p><h2>Start with the sound</h2><p>If the wheel area produces a high-pitched squeal or a grinding sound during normal braking, the pad material may already be close to the backing plate.</p><h3>Check pedal feel</h3><p>A longer stopping distance, vibration under foot, or a pedal that feels softer than usual should trigger a workshop inspection immediately.</p><ul><li>Inspect pad thickness at both front wheels.</li><li>Check the rotor face for scoring or heat spots.</li><li>Confirm caliper slide movement before fitting new pads.</li></ul><p>When replacing pads, always match the set to the vehicle year range and driving pattern.</p>',
    'https://images.example.com/blog/brake-pads-inspection.jpg',
    'Mechanic inspecting worn brake pads on a sedan',
    'Aisha Bello',
    'https://images.example.com/authors/aisha-bello.jpg',
    3,
    'published',
    '2026-02-12 09:00:00',
    184,
    '2026-02-11 14:20:00',
    '2026-02-12 09:00:00'
  ),
  (
    8302,
    8102,
    'Five Causes of Rough Idling in Popular Toyota Engines',
    'five-causes-of-rough-idling-in-popular-toyota-engines',
    'From vacuum leaks to tired ignition coils, these are the first checks workshops should make when a Toyota engine starts idling unevenly.',
    '<p>Rough idling often feels small at first, but it is usually an early warning that fuel, spark, or airflow is drifting out of spec.</p><h2>Common checks</h2><ol><li>Inspect intake hoses for splits and loose clamps.</li><li>Test ignition coils and spark plug condition.</li><li>Confirm throttle body cleanliness.</li><li>Check injector balance and fuel pressure.</li><li>Scan for sensor faults before changing parts.</li></ol><p>Documenting each step helps avoid replacing expensive components without proof.</p>',
    'https://images.example.com/blog/toyota-rough-idle.jpg',
    'Toyota engine bay during idle diagnostics',
    'Kunle Adebayo',
    'https://images.example.com/authors/kunle-adebayo.jpg',
    4,
    'published',
    '2026-02-26 10:30:00',
    221,
    '2026-02-24 12:10:00',
    '2026-02-26 10:30:00'
  ),
  (
    8303,
    8103,
    'OEM, Aftermarket, or Used: Choosing the Right Part for the Job',
    'oem-aftermarket-or-used-choosing-the-right-part-for-the-job',
    'A clear framework for deciding when an OEM part is worth the premium and when a trusted aftermarket or used option makes more sense.',
    '<p>Every buyer wants value, but the cheapest part is not always the most affordable once repeat labour and downtime are counted.</p><h2>Choose by risk</h2><p>Safety-critical parts like brake hydraulics, steering joints, and timing components should be sourced from the most reliable supply chain available.</p><h3>Compare three things</h3><ul><li>Vehicle usage and urgency.</li><li>Warranty support from the seller.</li><li>Availability of fitment confirmation.</li></ul><p>For cosmetic or non-critical items, a quality aftermarket option can be the practical choice.</p>',
    'https://images.example.com/blog/oem-vs-aftermarket.jpg',
    'Three boxed auto parts ready for comparison',
    'Mariam Okonkwo',
    'https://images.example.com/authors/mariam-okonkwo.jpg',
    4,
    'published',
    '2026-03-05 08:45:00',
    165,
    '2026-03-03 16:00:00',
    '2026-03-05 08:45:00'
  ),
  (
    8304,
    8104,
    'Preventive Maintenance Habits That Cut Fleet Downtime',
    'preventive-maintenance-habits-that-cut-fleet-downtime',
    'Simple inspection routines, stock planning, and service documentation can prevent delivery fleets from losing profitable operating days.',
    '<p>Fleet breakdowns usually come from missed basics rather than rare failures. Good operators win by being boring and consistent.</p><h2>Build repeatable routines</h2><p>Track mileage, tyre rotation, fluid checks, and brake inspection dates across every vehicle.</p><h3>Stock smart</h3><p>Keep fast-moving service items such as filters, brake pads, belts, and bulbs available before the next service window.</p><blockquote><p>Downtime compounds when one missing part keeps a vehicle parked for two extra days.</p></blockquote><p>A simple service log can expose patterns before they become route failures.</p>',
    'https://images.example.com/blog/fleet-maintenance-checklist.jpg',
    'Commercial vans lined up for service inspection',
    'Emeka Nnaji',
    'https://images.example.com/authors/emeka-nnaji.jpg',
    3,
    'published',
    '2026-03-19 11:15:00',
    142,
    '2026-03-17 09:40:00',
    '2026-03-19 11:15:00'
  ),
  (
    8305,
    8101,
    'Cabin and Engine Filters: Service Intervals That Make Sense in Dusty Cities',
    'cabin-and-engine-filters-service-intervals-that-make-sense-in-dusty-cities',
    'High dust conditions in Lagos, Kano, and Port Harcourt can shorten filter life far earlier than the interval printed in the handbook.',
    '<p>Dust, stop-and-go traffic, and long idling hours all reduce the useful life of service filters.</p><h2>Watch the environment</h2><p>Vehicles that operate near construction zones, industrial yards, or unpaved shoulders should have filters checked more often than standard schedules suggest.</p><ul><li>Inspect cabin filters during every air conditioning complaint.</li><li>Check engine filters at each oil change.</li><li>Replace early if airflow or fuel economy drops.</li></ul><p>Using the right filter part number is just as important as replacing it on time.</p>',
    'https://images.example.com/blog/filter-service-lagos.jpg',
    'Replacement cabin and engine filters on a workbench',
    'Aisha Bello',
    'https://images.example.com/authors/aisha-bello.jpg',
    3,
    'published',
    '2026-04-02 07:50:00',
    133,
    '2026-03-31 15:30:00',
    '2026-04-02 07:50:00'
  ),
  (
    8306,
    8102,
    'What a Weak Fuel Pump Sounds Like Before the Car Refuses to Start',
    'what-a-weak-fuel-pump-sounds-like-before-the-car-refuses-to-start',
    'Hard starts, whining from the tank area, and hesitation under load often point to a fuel delivery problem before total failure.',
    '<p>Fuel pump failure rarely arrives without warning. Drivers often notice longer cranking or a whining noise days before the vehicle stays parked.</p><h2>Key symptoms</h2><p>Look for hesitation during overtaking, surging under acceleration, or a drop in power while climbing.</p><h3>Confirm with tests</h3><p>Measure fuel pressure, inspect the relay circuit, and check filter restriction before replacing the pump assembly.</p><p>Documenting voltage and pressure saves time when the vehicle returns later with a related complaint.</p>',
    'https://images.example.com/blog/fuel-pump-warning-signs.jpg',
    'Fuel pressure gauge connected during diagnostics',
    'Kunle Adebayo',
    'https://images.example.com/authors/kunle-adebayo.jpg',
    3,
    'published',
    '2026-04-16 12:20:00',
    176,
    '2026-04-14 10:10:00',
    '2026-04-16 12:20:00'
  ),
  (
    8307,
    8103,
    'Checking Part Compatibility Before You Pay a Deposit',
    'checking-part-compatibility-before-you-pay-a-deposit',
    'The quickest way to avoid buying the wrong part is to confirm the chassis range, old part number, and engine code before payment.',
    '<p>Deposits move quickly in busy parts markets, which is why compatibility mistakes are still common.</p><h2>Confirm three references</h2><ol><li>Vehicle year range and trim.</li><li>Existing part number or stamped casting.</li><li>Engine and transmission variant.</li></ol><p>A clear workshop photo can help a seller confirm fitment before dispatch.</p><p>When in doubt, slow the transaction down and verify again.</p>',
    'https://images.example.com/blog/fitment-check-before-payment.jpg',
    'Mechanic comparing a part number against a phone order',
    'Mariam Okonkwo',
    'https://images.example.com/authors/mariam-okonkwo.jpg',
    2,
    'published',
    '2026-05-07 09:35:00',
    158,
    '2026-05-05 13:05:00',
    '2026-05-07 09:35:00'
  ),
  (
    8308,
    8104,
    'Stocking Fast-Moving Service Parts for Workshop Walk-Ins',
    'stocking-fast-moving-service-parts-for-workshop-walk-ins',
    'Small workshops can protect revenue by keeping a focused shelf of fast-moving filters, pads, plugs, and bulbs in verified fitment ranges.',
    '<p>Walk-in customers often decide where to service a car based on whether the workshop can finish the job on the same day.</p><h2>Start with repeat demand</h2><p>Track the models that come through your bay most often and keep only the service parts that move every week.</p><ul><li>Brake pads for common sedans.</li><li>Engine oil and air filters.</li><li>Spark plugs and ignition service items.</li><li>Bulbs and wiper blades.</li></ul><p>Dead stock ties up cash, so review the shelf every month.</p>',
    'https://images.example.com/blog/workshop-fast-moving-parts.jpg',
    'Workshop shelf stocked with filters and brake pads',
    'Emeka Nnaji',
    'https://images.example.com/authors/emeka-nnaji.jpg',
    3,
    'published',
    '2026-05-28 08:10:00',
    111,
    '2026-05-26 11:25:00',
    '2026-05-28 08:10:00'
  ),
  (
    8309,
    8105,
    'What Recent FX Pressure Means for Spare Parts Pricing',
    'what-recent-fx-pressure-means-for-spare-parts-pricing',
    'Exchange-rate movement affects landed cost, shelf pricing, and how aggressively workshops should plan upcoming stock purchases.',
    '<p>Parts businesses feel currency movement immediately because stock replacement cost changes before old shelf inventory is sold through.</p><h2>Watch procurement timing</h2><p>Importers and bulk buyers should compare restock urgency against expected FX volatility and current sales velocity.</p><h3>For smaller buyers</h3><p>It helps to secure fast-moving maintenance items earlier when possible instead of waiting for urgent demand.</p><p>Good data and disciplined reorder points protect margins better than guesswork.</p>',
    'https://images.example.com/blog/fx-pressure-spare-parts.jpg',
    'Auto parts boxes stacked inside a warehouse',
    'Tolu Salami',
    'https://images.example.com/authors/tolu-salami.jpg',
    3,
    'published',
    '2026-06-11 10:05:00',
    196,
    '2026-06-09 09:15:00',
    '2026-06-11 10:05:00'
  ),
  (
    8310,
    8101,
    'Why Shock Absorbers Should Be Replaced in Pairs',
    'why-shock-absorbers-should-be-replaced-in-pairs',
    'Replacing only one worn shock can leave the vehicle unstable under braking, cornering, and rough-road rebound.',
    '<p>Drivers often ask to replace only the visibly weak shock to save money, but mismatched damping can create a second problem immediately.</p><h2>Balance matters</h2><p>Shocks on the same axle should react at the same rate when the vehicle loads, brakes, or crosses uneven roads.</p><h3>Inspection checklist</h3><ul><li>Check bush wear and mount condition.</li><li>Inspect tyres for cupping.</li><li>Confirm there is no oil leakage on the new matching side.</li></ul><p>Pair replacement protects both comfort and control.</p>',
    'https://images.example.com/blog/replace-shocks-in-pairs.jpg',
    'Pair of new rear shock absorbers on a bench',
    'Aisha Bello',
    'https://images.example.com/authors/aisha-bello.jpg',
    3,
    'published',
    '2026-06-26 07:40:00',
    149,
    '2026-06-24 12:00:00',
    '2026-06-26 07:40:00'
  ),
  (
    8311,
    8102,
    'Battery, Alternator, or Starter: A Simple No-Start Triage Guide',
    'battery-alternator-or-starter-a-simple-no-start-triage-guide',
    'A no-start complaint becomes easier to solve when workshops separate crank issues from charging faults and power supply problems first.',
    '<p>The fastest diagnostic wins usually come from defining exactly what the vehicle does when the key is turned.</p><h2>Ask the first question</h2><p>Does the engine crank strongly, click once, or stay completely silent? That answer narrows the path quickly.</p><ol><li>Load test the battery.</li><li>Check voltage drop at the starter circuit.</li><li>Confirm alternator output after the engine starts.</li></ol><p>Clear process prevents unnecessary parts replacement.</p>',
    'https://images.example.com/blog/no-start-triage.jpg',
    'Technician testing battery voltage with a multimeter',
    'Kunle Adebayo',
    'https://images.example.com/authors/kunle-adebayo.jpg',
    3,
    'published',
    '2026-07-10 11:00:00',
    207,
    '2026-07-08 15:45:00',
    '2026-07-10 11:00:00'
  ),
  (
    8312,
    8103,
    'How to Compare Quotes From Two Different Parts Sellers',
    'how-to-compare-quotes-from-two-different-parts-sellers',
    'Price alone is not enough. Fitment confidence, delivery timing, warranty support, and return terms all belong in the comparison.',
    '<p>Two quotes that look close on price can be very different once hidden costs and delivery risk are considered.</p><h2>Compare like for like</h2><p>Confirm whether each seller is pricing the same brand tier, the same fitment range, and the same delivery promise.</p><h3>Important checks</h3><ul><li>Return window and restocking terms.</li><li>Who covers damaged-in-transit replacement.</li><li>Whether the item is actually in stock now.</li></ul><p>Written confirmation helps if the order needs to be disputed later.</p>',
    'https://images.example.com/blog/compare-parts-quotes.jpg',
    'Two written parts quotations on a desk',
    'Mariam Okonkwo',
    'https://images.example.com/authors/mariam-okonkwo.jpg',
    3,
    'published',
    '2026-07-24 09:25:00',
    128,
    '2026-07-22 14:55:00',
    '2026-07-24 09:25:00'
  ),
  (
    8313,
    8105,
    'Draft: Mapping the Busy Season for Brake and Suspension Demand',
    'draft-mapping-the-busy-season-for-brake-and-suspension-demand',
    'Internal planning note on seasonal patterns for brake and suspension parts.',
    '<p>This draft outlines seasonal demand signals for workshop operators and retail sellers.</p><p>It is intentionally unpublished and still being edited.</p>',
    'https://images.example.com/blog/draft-demand-patterns.jpg',
    'Spreadsheet and workshop stock shelves',
    'Tolu Salami',
    'https://images.example.com/authors/tolu-salami.jpg',
    1,
    'draft',
    NULL,
    0,
    '2026-08-01 10:00:00',
    '2026-08-03 12:00:00'
  ),
  (
    8314,
    8104,
    'Draft: Workshop Receiving Checklist for Delivered Parts',
    'draft-workshop-receiving-checklist-for-delivered-parts',
    'A working draft for workshops that want a standard receiving process before parts enter the shelf.',
    '<p>This draft captures shelf receiving steps that will later be turned into a printable checklist.</p><p>Images and examples are still pending.</p>',
    'https://images.example.com/blog/draft-receiving-checklist.jpg',
    'Workshop staff checking boxes after delivery',
    'Emeka Nnaji',
    'https://images.example.com/authors/emeka-nnaji.jpg',
    1,
    'draft',
    NULL,
    0,
    '2026-08-05 09:00:00',
    '2026-08-06 10:45:00'
  ),
  (
    8315,
    8105,
    'Scheduled: How New Port Handling Changes Could Affect Lead Times',
    'scheduled-how-new-port-handling-changes-could-affect-lead-times',
    'Scheduled analysis of shipping and handling changes that may affect spare parts arrival windows.',
    '<p>This post is scheduled for publication after final review of importer interviews and shipping notes.</p><p>The copy is complete but intentionally hidden until the release date.</p>',
    'https://images.example.com/blog/scheduled-port-handling-update.jpg',
    'Shipping containers at a seaport',
    'Tolu Salami',
    'https://images.example.com/authors/tolu-salami.jpg',
    2,
    'published',
    '2026-09-05 08:00:00',
    0,
    '2026-08-18 11:20:00',
    '2026-08-19 09:00:00'
  )
ON DUPLICATE KEY UPDATE
  category_id = VALUES(category_id),
  title = VALUES(title),
  slug = VALUES(slug),
  excerpt = VALUES(excerpt),
  body = VALUES(body),
  featured_image_url = VALUES(featured_image_url),
  featured_image_alt = VALUES(featured_image_alt),
  author_display_name = VALUES(author_display_name),
  author_avatar_url = VALUES(author_avatar_url),
  read_time_minutes = VALUES(read_time_minutes),
  status = VALUES(status),
  published_at = VALUES(published_at),
  view_count = VALUES(view_count),
  created_at = VALUES(created_at),
  updated_at = VALUES(updated_at);
